main:
  - name: About
    url: /
    weight: 10
  - name: News
    url: /#news
    weight: 20
  - name: Publications
    url: /#papers
    weight: 30
  - name: Honors
    url: /#honors
    weight: 40
  - name: Blogs
    url: /#blogs
    weight: 50
